image:
  - Visual Studio 2019
  - Visual Studio 2013

version: 3.31.{build}

environment:
    matrix:
      - GEN: -A Win32 -G "Visual Studio 16 2019"
      - GEN: -G "Visual Studio 16 2019"
      - GEN: -G "Visual Studio 12 2013"
      - GEN: -G "Visual Studio 12 2013 Win64"
matrix:
  exclude:
    - image: Visual Studio 2019
      GEN: -G "Visual Studio 12 2013"
    - image: Visual Studio 2019
      GEN: -G "Visual Studio 12 2013 Win64"
    - image: Visual Studio 2013
      GEN: -A Win32 -G "Visual Studio 16 2019"
    - image: Visual Studio 2013
      GEN: -G "Visual Studio 16 2019"
install:
  # Remove the VS Xamarin targets to reduce AppVeyor specific noise in build
  # logs.  See also http://help.appveyor.com/discussions/problems/4569
  # - del "C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - git submodule update --init --recursive

build_script:
  - cd build
  - mkdir build_win
  - cd build_win
  - cmake --version
  - cmake %GEN% ../../
  - cmake --build . --config Release --clean-first
