image:
  - Visual Studio 2013

version: 3.37.7.{build}

environment:
    global:
      BUILD_TYPE: Release
    matrix:
      - BUILD_ARCH: x86
      - BUILD_ARCH: x64

install:
  # Remove the VS Xamarin targets to reduce AppVeyor specific noise in build
  # logs.  See also http://help.appveyor.com/discussions/problems/4569
  # - del "C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - git submodule update --init --recursive

build_script:
  - ps: .\ci\build.ps1
