osx_image: xcode11
language: cpp
matrix:
  include:
    - os: osx
      env: 
        - BUILD_TARGET=osx
    - os: linux
      env: 
        - BUILD_TARGET=linux
    - os: osx
      env: 
        - BUILD_TARGET=ios
    - os: linux
      env:
        - BUILD_TARGET=android

install:
  - travis/install.sh

script:
  - travis/build.sh
