name: docs

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      versions:
        description: 'Please specific active versions'
        # Default value if no value is explicitly provided
        default: '3.37.1,3.37.2,3.37.3'
        # Input has to be provided for the workflow to run
        required: true
      comment:
        description: 'Comment only'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false
env:
  DOCS_CI: 1
  PYTHON_VERSION: 3.x

jobs:
  documentation:
    name: Build docs
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Install missing fonts
        run: |
          wget https://github.com/simdsoft/fontlist/releases/download/v1.0/fontlist.zip
          unzip fontlist.zip
          mkdir -p ~/.fonts/
          cp fontlist/* ~/.fonts/
      - name: Deploy docs
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
          ACTIVE_VERSIONS: ${{ github.event.inputs.versions }}
        run: |
          git config user.name "docs-bot"
          git config user.email "docs-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          source ci/docs.sh
