name: linux

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  TRAVIS_OS_NAME: linux
  BUILD_TARGET: linux
  # Simple let github action to build all (TODO: optimize in the future)
  TRAVIS_PULL_REQUEST: true
  BUILD_TYPE: Release
  GITHUB_CI: true

jobs:
  build:
    if: "contains(github.event.commits[0].message, '[ci build]')"
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: travis/install.sh

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: travis/build.sh
